apiVersion: v1
kind: Pod
metadata:
  name: cm-test-app
spec:
  containers:
  - name: cm-test-app
    image: kubeguide/tomcat-app:v1
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: serverxml                   # 引用Volume的名称
      mountPath: /configfiles           # 挂载到容器内的目录
  volumes:
  - name: serverxml                     # 定义Volume的名称
    configMap:
      name: cm-appconfigfiles           # 使用ConfigMap"cm-appconfigfiles"