apiVersion: v1
kind: Pod
metadata:
  name: cm-test-pod
spec:
  containers:
  - name: cm-test
    image: bustbox
    command: ["/bin/sh", "-c", "env | grep APP"]
    env:
    - name: APPLOGLEVEL         # 定义环境变量的名称
      valueFrom:                # key "apploglevel" 对应的值
        configMapKeyRef:        
          name: cm-appvars      # 环境变量的值取自 cm-appvars
          key: apploglevel      # key为apploglevel
    - name: APPDATADIR          # 定义环境变量的名称
      valueFrom:                # key "appdatadir" 对应的值
        configMapKeyRef:
          name: cm-appvars      # 环境变脸的值取自cm-appvars
          key: appdatadir       # key为appdatadir
  restartPolicy: Never