apiVersion: v1
kind: Pod
metadata:
  name: cm-test-pod
spec:
  containers:
  - name: cm-test
    image: bustbox
    command: ["/bin/sh", "-c", "env"]
    envFrom:
    - configMapRef:
      name: cm-appvars       # 根据cm-appvars中的key=value自动生成环境变量
  restartPolicy: Never