apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:x-admin, applications, *, */*, allow
    p, role:x-admin, clusters, get, *, allow
    p, role:x-admin, repositories, get, *, allow
    p, role:x-admin, repositories, create, *, allow
    p, role:x-admin, repositories, update, *, allow
    p, role:x-admin, repositories, delete, *, allow
    p, role:x-admin, projects, get, *, allow
    p, role:x-admin, projects, create, *, allow
    p, role:x-admin, projects, update, *, allow
    p, role:x-admin, projects, delete, *, allow
    p, role:x-admin, logs, get, *, allow
    p, role:x-admin, exec, create, */*, allow

    g, kingxhj, role:x-admin
    g, z4hd, role:x-admin
