apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-argocd
spec:
  acme:
    email: komodoensis@126.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-argocd
    solvers:
    - dns01:
        cloudDNS:
          project: my-project
          serviceAccountSecretRef:
            name: prod-clouddns-svc-acct-secret
            key: service-account.json