apiVersion: rabc.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: configmap-updater
rules:
- apiGroups: [""]
  resources: ["configmap"]
  resourcesNames: ["my-configmap"]
  verbs: ["update", "get"]