apiVersion: v1
kind: Config
clusters:                                           # 远程授权服务
  - name: name-of-remote-authz-service
    cluster:
      certificate-authority: /path/to/ca.pem        # 验证远程授权服务的CA证书
      server: https://authz.example.com/authorize   # 远程授权fuwuURL，必须使用HTTPS
users:                                              # API Server的信息
  - name: name-of-api-server
    user:
      client-certificate: /path/to/cert.pem         # Webhook插件使用的客户端CA证书
      client-key: /path/to/key.pem                  # Webhook插件使用的客户端CA私钥
current-context: webhook
contexts:
- context:
    cluster: name-of-remote-authz-service
    user: name-of-api-server
  name: webhook