spec:
  ports:
  - appProtocol: http
    name: http
    nodePort: 80
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 443
    port: 443
    protocol: TCP
    targetPort: https